chameleonsofttest/protected/models/Books.php
<?php

/**
 * This is the model class for table "books".
 *
 * The followings are the available columns in table 'books':
 * @property integer $id
 * @property string $name
 * @property string $date_create
 * @property string $date_update
 * @property string $preview
 * @property string $date
 * @property integer $author_id
 */
class Books extends CActiveRecord
{

	public $author;
	public $datefrom;
	public $dateto;
	public $preview_img;
    public $loadSPS1;

	public function getAuthor()
	{
		return $this->authors->firstName . ' ' . $this->authors->lastName;
	}


	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'books';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, date_update, preview, date, author_id', 'required'),
			array('author_id', 'numerical', 'integerOnly'=>true),
			array('name, preview', 'length', 'max'=>255),
			array('date_create', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, date_create, date_update, preview, date, author_id, author, datefrom, dateto', 'safe', 'on'=>'search'),
			array('preview_img', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true, 'on'=>'update'),
			array('preview_img', 'length', 'max'=>255, 'on'=>'insert,update'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'authors' => array(self::BELONGS_TO, 'Authors', 'author_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Название',
			'date_create' => 'Дата добавления',
			'date_update' => 'Дата обновления',
			'preview' => 'Превью',
			'date' => 'Дата выхода книги',
			'author_id' => 'Author ID',
			'author' => 'Автор',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria = new CDbCriteria;
		$sort = new CSort;

		$criteria->with = array(
			'authors' => array()
		);

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('date_create',$this->date_create,true);
		$criteria->compare('date_update',$this->date_update,true);
		$criteria->compare('preview',$this->preview,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('author_id',$this->author_id);
		$criteria->compare('firstname, lastname', $this->author, true);


		if (!empty($this->datefrom) && empty($this->dateto)) {
			$criteria->addCondition("date >= '{$this->datefrom}'");
		} elseif(!empty($this->dateto) && empty($this->dateto)) {
			$criteria->addCondition("date <= '{$this->dateto}'");
		} elseif(!empty($this->dateto) && !empty($this->dateto)) {
			$criteria->addCondition(
				"date  >= '{$this->datefrom}' and date <= '{$this->dateto}'");
		}

		$sort->sortVar = get_class($this) . '_sort';
		$sort->attributes = array(
			'author'=>array(
				'asc'=>'firstname, lastname',
				'desc'=>'firstname desc, lastname desc',
			),
			'*',
		);

		return new CActiveDataProvider($this, array(
			'pagination'=>array('pageSize'=>10),
			'criteria'=>$criteria,
			'sort'=>$sort,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Books the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

chameleonsofttest/protected/controllers/BooksController.php
<?php

class BooksController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete', 'ajaxcontent', 'ajaximgsrc'),
				'users'=>array('admin', 'ajaxcontent', 'ajaximgsrc'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}


	public function actionAjaxcontent($id)
	{
        header('Content-type: application/json');

		$model = $this->loadModel($id);
        $data = [];
        $data['id'] = $model->id;
        $data['name'] = $model->name;
        $data['preview'] = Yii::app()->baseUrl . "/images/books/thumbnails/" . $model->preview;
        $data['author'] = Authors::model()->findByPk($model->author_id)->author;
        $data['date'] = $model->date;
        $data['date_create'] = $model->date_create;

        echo CJSON::encode($data);
	}

    public function actionAjaximgsrc($id)
    {
        header('Content-type: application/json');
        $model = $this->loadModel($id);
        $imgSrc = array('src'=> Yii::app()->baseUrl ."/images/books/originals/" .
                                $model->preview,
                        	'name' => $model->name,);
        echo CJSON::encode($imgSrc);
    }


	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Books;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Books']))
		{
			$model->attributes=$_POST['Books'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Books']))
		{
			$_POST['Books']['preview_img'] = $model->preview_img;
			$model->attributes=$_POST['Books'];

			$uploadedFile=CUploadedFile::getInstance($model,'preview_img');


			if($model->save())
				if(!is_null($uploadedFile))  // check if uploaded file is set or not
				{
					$uploadedFile->saveAs(Yii::app()->basePath.'/../images/books/originals/'.$model->preview);
					$image = new \Eventviva\ImageResize(Yii::app()->basePath.'/../images/books/originals/'.$model->preview);
					$image->resizeToWidth(100);
					$image->save(Yii::app()->basePath.'/../images/books/thumbnails/'.$model->preview);

				}
				$this->redirect(array('admin', 'loadSPS' => 1));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Books');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{

		if (isset($_GET['loadSPS'])) {
            if (!isset($_GET['loadSPS1'])) {
                self::initSearchPageSort('Books', 'load');
            } else {
                unset($_GET['loadSPS1']);
            }
			unset($_GET['loadSPS']);
		}

		self::initSearchPageSort('Books');

		unset(Yii::app()->request->cookies['datefrom']);
		unset(Yii::app()->request->cookies['dateto']);

		$model=new Books('search');
		$model->unsetAttributes();  // clear any default values

		if(isset($_GET['datefrom']) && isset($_GET['dateto']))
		{

			Yii::app()->request->cookies['datefrom'] = new CHttpCookie('datefrom', $_GET['datefrom']);
			Yii::app()->request->cookies['dateto'] = new CHttpCookie('dateto', $_GET['dateto']);
			$model->datefrom = $_GET['datefrom'];
			$model->dateto = $_GET['dateto'];
		}

		if(isset($_GET['Books']))
			$model->attributes=$_GET['Books'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Books the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Books::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Books $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='books-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

    //Explanation:  http://www.yiiframework.ru/forum/viewtopic.php?t=3630
	protected static function initSearchPageSort($modelName, $action = 'save') {
		/** @var WebUser $webUser */
		$webUser = Yii::app()->user;
		$params = array(
			"{$modelName}",
			"{$modelName}_page",
			"{$modelName}_sort",
		);
		foreach ($params as $p) {
			$_p = "_{$p}";
			switch ($action) {
				case 'save' :
					if (isset($_GET[$p])) {
						$webUser->setState($_p, $_GET[$p]);
					} else {
						$webUser->setState($_p, null);
					}
					break;
				case 'load' :
					$data = $webUser->getState($_p);
					if ( isset($data) ) {
						$_GET[$p] = $data;
					}
					break;
				case 'reset' :
					$webUser->setState($_p, null);
					break;
			}
		}
	}

}

chameleonsofttest/protected/views/books/_form.php
<?php
/* @var $this BooksController */
/* @var $model Books */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'books-form',

	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
	'htmlOptions' => array(
		'enctype' => 'multipart/form-data',
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'preview'); ?>
		<?php echo CHtml::activeFileField($model, 'preview_img'); ?>
		<?php echo $form->error($model,'preview'); ?>
	</div>
	<?php if($model->isNewRecord!='1'){ ?>
	<div class="row">
		<?php echo CHtml::image(Yii::app()->request->baseUrl.
			'/images/books/thumbnails/'.$model->preview,"preview",array("max-width"=>'100px')); }?>
	</div>

	<div class="row">
        <?php echo $form->labelEx($model,'date'); ?>

		<?php
		$this->widget('zii.widgets.jui.CJuiDatePicker',array(
			'model'=>$model,
			'name'=>'date',
			'attribute' => 'date',
            'options'=>array(
                'showAnim'=>'fold',
				'dateFormat'=>'yy-mm-dd',
            ),
        ));
		?>
		<?php echo $form->error($model,'date'); ?>
	</div>

	<div class="row">
        <?php echo $form->dropDownList($model,'author_id',
            CHtml::listData(Authors::model()->findAll(array('order' => 'firstname, lastname')),'id','author'),
            array('empty'=>'--Автор--'));
        ?>
		<?php echo $form->error($model,'author_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

chameleonsofttest/protected/views/books/_search.php
<?php
/* @var $this BooksController */
/* @var $model Books */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'enableAjaxValidation'=>true,
));


CHtml::hiddenField('loadSPS1' , '1', array('id' => 'hiddenInput'));
//$form->hiddenField($model,'loadSPS1', array('value'=>'1'));

?>

    <input type="hidden" name="loadSPS1" value="1"/>

	<div class="row">
        <?php echo $form->dropDownList($model,'author_id',
                   CHtml::listData(Authors::model()->findAll(array('order' => 'firstname, lastname')),'id','author'),
                  array('empty'=>'--Автор--'));
        ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255, 'placeholder'=>'название книги')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date'); ?>

		<?php
		$this->widget('zii.widgets.jui.CJuiDatePicker',array(
		'name'=>'datefrom',
		'value'=> isset(Yii::app()->request->cookies['datefrom']) ? Yii::app()->request->cookies['datefrom']->value : '',
		'language'=>'ru',
		'options'=>array(
		'showAnim'=>'fold',
		'dateFormat'=>'yy-mm-dd',
		),
		'htmlOptions'=>array(
			'style'=>'height:25px;'
		),
		));
		?>
		до
		<?php
		$this->widget('zii.widgets.jui.CJuiDatePicker',array(
			'name'=>'dateto',
			'value'=>isset(Yii::app()->request->cookies['dateto']) ? Yii::app()->request->cookies['dateto']->value : '',
			'language'=>'ru',
			'options'=>array(
				'showAnim'=>'fold',
				'dateFormat'=>'yy-mm-dd',
			),
			'htmlOptions'=>array(
				'style'=>'height:25px;'
			),
		));
		?>
		<div style="float: right;">
		<?php echo CHtml::submitButton('Искать'); ?>
		</div>	
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

chameleonsofttest/protected/views/books/_view.php
<?php
/* @var $this BooksController */
/* @var $data Books */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date_create')); ?>:</b>
	<?php echo CHtml::encode($data->date_create); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date_update')); ?>:</b>
	<?php echo CHtml::encode($data->date_update); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('preview')); ?>:</b>
	<?php echo CHtml::encode($data->preview); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('author_id')); ?>:</b>
	<?php echo CHtml::encode($data->author_id); ?>
	<br />


</div>

chameleonsofttest/protected/views/books/admin.php
<?php
/* @var $this BooksController */
/* @var $model Books */

$this->breadcrumbs = array(
    'Books' => array('index'),
    'Manage',
);

/*$this->menu = array(
    array('label' => 'List Books', 'url' => array('index')),
    array('label' => 'Create Books', 'url' => array('create')),
);*/

Yii::app()->clientScript->registerScript(
    'search',
    "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#books-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
"
);
?>

<h1>Управление списком книг</h1>

<!--<p>
    You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>,
    <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
    or <b>=</b>) at the beginning of each of your search values to specify how
    the comparison should be done.
</p>
-->

<?php //echo CHtml::link(
    //'Advanced Search',
    //'#',
    //array('class' => 'search-button')
//); ?>
<!--<div class="search-form" style="display:none">-->
    <div class="search-form" >
    <?php $this->renderPartial(
        '_search',
        array(
            'model' => $model,
        )
    ); ?>
</div><!-- search-form -->

<?php
$image
    = 'CHtml::image(Yii::app()->baseUrl ."/images/books/thumbnails/" .$data->preview,"",array(\'max_width\'=>\'100\'))';
$imageLink
    = 'CHtml::ajaxLink(
    '.$image.',
    array(\'books/ajaximgsrc\', \'id\' => $data->primaryKey ),
    array(
        \'type\' => \'POST\',
        \'data\'=>array(\'update\'=>TRUE),
        \'success\' => \'function(data){
            $("#previewModal").modal("show");
            $("#preview-image").attr("src",data.src);
            $("#preview-image-descr").html(data.name);
        }\',
    ))';

$this->widget(
    'zii.widgets.grid.CGridView',
    array(
        'id'           => 'books-grid',
        'dataProvider' => $model->search(),
        'ajaxUpdate'   => false,
        'columns'      => array(
            'id',
            'name',
            array(
                'labelExpression' => $imageLink,
                'header'          => 'Превью',
                'class'           => 'CLinkColumn',
            ),
            array(
                'name'   => 'author',
                'header' => CHtml::encode($model->getAttributeLabel('author')),
                'value'  => '$data->authors->author',
                'filter'=> CHtml::activeTextField($model, 'author'),
            ),
            array(
                'name'=>'date',
                'value' => 'Yii::app()->dateFormatter->format(\'d MMMM yyyy\', $data->date)',
            ),
            array(
              'name'=>'date_create',
              'value' => 'Yii::app()->dateFormatter->format(\'d MMMM yyyy\', $data->date_create)',
            ),
            array(
                'header'=>'Кнопки действий',
                'class'                => 'CButtonColumn',
                'template'             => '{view} {update} {delete}',
                'deleteButtonImageUrl' => false,
                'updateButtonImageUrl' => false,
                'viewButtonImageUrl'   => false,
                'buttons'              => array
                (
                    'update' => array
                    (
                        'label' => '[ред]',
                    ),
                    'view'   => array
                    (
                        'label' => '[просм]',
                        'url'   => 'Yii::app()->createUrl("books/ajaxcontent", array("id"=>$data["id"]))',
                        'click' => "function(){ $.ajax({
                                type:'POST',
                                cache:false,
                                url  : $(this).attr('href'),
                                success: function(data) {
                                  $('#detailViewModal').modal('show');
                                  $('#detail-view-id').html(data.id);
                                  $('#detail-view-name').html(data.name);
                                  $('#detail-view-image').attr('src',data.preview);
                                  $('#detail-view-author').html(data.author);
                                  $('#detail-view-date').html(data.date);
                                  $('#detail-view-date-create').html(data.date_create);
                                },
                                });
                              return false;}",
                    ),
                    'delete' => array
                    (
                        'label' => '[удл]',
                    ),

                ),
            ),
        ),
    )
);
?>

<?php $this->widget(
    'bootstrap.widgets.TbModal',
    array(
        'id'      => 'previewModal',
        'header'  => 'Превью',
        'content' => '<div><img id="preview-image" style="max-width: 100%;" src=""></div><div id="preview-image-descr">TEST</div>',
        'footer'  => array(
            TbHtml::button('Close', array('data-dismiss' => 'modal')),
        ),
    )
); ?>

<?php $this->widget(
    'bootstrap.widgets.TbModal',
    array(
        'id'      => 'detailViewModal',
        'header'  => 'Детальный просмотр',
        'content' => '<div id="detail-view-content">
<table class="table table-striped">
  <tbody>
    <tr>
      <th scope="row">ID</th>
      <td><div id="detail-view-id"></div></td>
    </tr>
    <tr>
      <th scope="row">Название</th>
      <td><div id="detail-view-name"></div></td>
    </tr>
    <tr>
      <th scope="row">Превью</th>
      <td><img id="detail-view-image" style="max-width: 100px;" src=""/></td>
    </tr>
    <tr>
      <th scope="row">Автор</th>
      <td><div id="detail-view-author"></div></td>
    </tr>
    <tr>
      <th scope="row">Дата выхода книги</th>
      <td><div id="detail-view-date"></div></td>
    </tr>
    <tr>
      <th scope="row">Дата добавления</th>
      <td><div id="detail-view-date-create"></div></td>
    </tr>
  </tbody>
</table></div>',
        'footer'  => array(
            TbHtml::button('Close', array('data-dismiss' => 'modal')),
        ),
    )
); ?>

chameleonsofttest/protected/views/books/create.php
<?php
/* @var $this BooksController */
/* @var $model Books */

$this->breadcrumbs=array(
	'Books'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Books', 'url'=>array('index')),
	array('label'=>'Manage Books', 'url'=>array('admin')),
);
?>

<h1>Create Books</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

chameleonsofttest/protected/views/books/index.php
<?php
/* @var $this BooksController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Books',
);

/*$this->menu=array(
	array('label'=>'Create Books', 'url'=>array('create')),
	array('label'=>'Manage Books', 'url'=>array('admin')),
);*/
?>

<h1>Books</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

chameleonsofttest/protected/views/books/update.php
<?php
/* @var $this BooksController */
/* @var $model Books */
/*
$this->breadcrumbs=array(
	'Books'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);*/
/*
$this->menu=array(
	array('label'=>'List Books', 'url'=>array('index')),
	array('label'=>'Create Books', 'url'=>array('create')),
	array('label'=>'View Books', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Books', 'url'=>array('admin')),
);*/
?>

<h1>Update Books <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

chameleonsofttest/protected/views/books/view.php
<?php
/* @var $this BooksController */
/* @var $model Books */

$this->breadcrumbs=array(
	'Books'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Books', 'url'=>array('index')),
	array('label'=>'Create Books', 'url'=>array('create')),
	array('label'=>'Update Books', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Books', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Books', 'url'=>array('admin')),
);
?>

<h1>View Books #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'date_create',
		'date_update',
		'preview',
		'date',
		'author_id',
	),
)); ?>